### ISSUE TITLE
Is it possible to complete Java classes?

### ISSUE THREAD

**Issue by hifall** [clojure-lsp/clojure-lsp#20] opened 2019-02-04 09:30 UTC
Say I access Java classes like this:

```
(println (doto (java.util.Stack.)
  (.push 42)
  (.push 13)
  (.push 7)))
```

I can't seem to complete `java.util.`. Is this supported by this clojure-lsp?

Thanks!

**Comment by snoe** [comment] 2019-02-05 06:36
It would be possible, I cheat a bit with the java.lang classes here https://github.com/snoe/clojure-lsp/blob/master/src/clojure_lsp/clojure_core.clj

Basically rt.jar would need to be added to the list of classpath jars  https://github.com/snoe/clojure-lsp/blob/master/src/clojure_lsp/handlers.clj#L98 and then use something like https://stackoverflow.com/a/14451505 to add usages of .class files (that have no clj pair).

**Comment by hifall** [comment] 2019-02-05 07:18
So this sounds there is no out-of-the-box way of doing it, until you implement what's described in the above SO link?

**Comment by snoe** [comment] 2019-02-05 15:02
Correct, at the moment the only completions you get are for java.lang

**Comment by ericdallo** [comment] 2020-06-20 16:37
java.lang completions seems to work for me with `lsp-mode` for Emacs, can you test it again @hifall ?

**Comment by ericdallo** [comment] 2021-02-05 03:00
Closing this since I can't reproduce the issue with latest release, LMK if any issues

**Closed by ericdallo** 2021-02-05 03:00 UTC
