### ISSUE TITLE
nix flake broken on aarch64-darwin

### ISSUE THREAD

**Issue by jasonjckn** [clojure-lsp/clojure-lsp#1404] opened 2022-12-05 04:29 UTC
**Describe the bug**
Installation broken

**To Reproduce**

1. $ nix shell github:clojure-lsp/clojure-lsp -c clojure-lsp --version

**Actual behavior**
```
error: builder for '/nix/store/hz37xnnb9z6h6djf69g944zihpqvw895-clojure-lsp-DEV.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/vmmrlna1cjdx28xxx63si00mx7lwfv3k-3pjviq6s4fy5mwlqily40kfjh219h6v9-source
       > source root is 3pjviq6s4fy5mwlqily40kfjh219h6v9-source
       > patching sources
       > Execution error (ExceptionInfo) at cljnix.utils/throw+ (utils.clj:22).
       > "Can't expand full sha" {:lib io.github.clojure/tools.build, :node {:git/url "https://github.com/clojure/tools.build.git", :tag "v0.8.5", :sha "9c738da"}}
       >
       >
       > Full report at:
       > /var/folders/y4/87_0dw1j7qgcv1gzb0kypycr0000gn/T/clojure-6553883098006277384.edn
       For full logs, run 'nix log /nix/store/hz37xnnb9z6h6djf69g944zihpqvw895-clojure-lsp-DEV.drv'.
error: 1 dependencies of derivation '/nix/store/app7v3c8zbd5gfzkws8gkjh1bdpvgh3x-clojure-lsp-DEV.drv' failed to build

```

**Expected behavior**
should work

**User details (please complete the following information):**
 - OS: macos / aarch64-darwin
 - Version: latest in master

**Additional context**
tools.build recently did a published jar release, you no longer need to rely on git SHA's, that might resolve this issue too.

**Comment by ericdallo** [comment] 2022-12-05 12:32
Thanks, but this is a duplicate of https://github.com/clojure-lsp/clojure-lsp/issues/1373

**Closed by ericdallo** 2022-12-05 12:32 UTC
Labels: bug, API
