### ISSUE TITLE
Test harness for stdin/stdout

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#285] opened 2021-01-28 05:48 UTC
From https://github.com/clojure-lsp/clojure-lsp/issues/283

I think we need to have a test harness that operates on rpc with stdin/stdout. We should be able to do something (this is a guess) like `lein run > results.txt < rpc-test.txt` .

I'm not sure if the `with-out-str` solution in the linked issue will keep the `*out*` binding across threads.

**Comment by ericdallo** [comment] 2021-01-28 10:54
Yeah, like an integration test, clj-kondo has similar tests

**Comment by ericdallo** [comment] 2021-02-03 12:08
I just realized that this is a duplicate of #289 that I'm WIP, I'll close this to track on that issue (even if this was the first one 😅 )

**Closed by ericdallo** 2021-02-03 12:08 UTC
