### ISSUE TITLE
Bug: content deleted during format

### ISSUE THREAD

**Issue by gjabell** [clojure-lsp/clojure-lsp#127] opened 2020-04-25 14:48 UTC
I'm running clojure-lsp in conjunction with Neovim + LanguageClient-neovim. When calling the language server's format functionality, the entire contents of the file is deleted but only if the file is unmodified. So:

- make some changes
- call languageserver's format function => contents is formatted
- save file
- call languageserver's format function => contents is deleted
- press undo => file is restored but *modified*
- call languageserver's format function => contents is formatted

As long as the file is in a modified state, everything works fine. I'm not sure whether this is specifically an issue with clojure-lsp or an interaction with my language client plugin, although I haven't had this issue with other language servers.

Thanks for your work on adding this to the Clojure ecosystem! Please let me know if there's any testing or logs I can provide.

**Comment by snoe** [comment] 2020-04-30 14:25
@gjabell can you try to reproduce this with a single, small file? My suspicion is that it might have to do with an unparseable file, like an unbalanced map `{:foo}`

**Comment by gjabell** [comment] 2020-05-03 20:53
Hey @snoe, thanks for looking into this. I can reproduce it with the following file (default `core.clj` generated by Leiningen):

```clojure
(ns bug.core)

(defn foo
  "I don't do a whole lot."
  [x]
  (println x "Hello, World!"))
```

It looks like it doesn't have the issue when the file is first loaded, but is reproduceable at any point after that if the file has been modified and then saved. I also tried disable all plugins in Neovim except LanguageClient-neovim and the behavior persists.

**Comment by osleg** [comment] 2020-05-26 12:18
I can add that exactly same behavior happens with Coc.nvim as LSP client

**Comment by ericdallo** [comment] 2020-05-26 12:40
This never happened to me on Emacs with `lsp-mode`.
Maybe is a bug on how lsp for vim works?

**Comment by snoe** [comment] 2020-05-27 14:57
@osleg what command are you using in coc.nvim?  I still had trouble reproducing...

**Comment by ericdallo** [comment] 2020-06-20 16:16
Well, I can confirm that this happened to me this week with `lsp-mode` for Emacs, but I could not reproduce it again...

**Comment by osleg** [comment] 2020-06-21 11:49
@snoe the easiest way to reproduce it for me is to do
`au FileType clojure autocmd BufWritePre <buffer> call CocActionAsync('format')`

Add some new lines in a big clojure file -> `:w<cr>i`. For me it happens 8 out of 10 times.

**Comment by ericdallo** [comment] 2020-06-21 14:21
Yeah, I remember only having this on a big file

**Comment by ericdallo** [comment] 2020-06-22 20:53
c/c @snoe

![clean-ns-bug](https://user-images.githubusercontent.com/7820865/85334134-215a5280-b4b1-11ea-942f-7d87e8b6d5bf.gif)

**Comment by ericdallo** [comment] 2021-02-07 23:11
Ok, this was fixed some time ago and I never saw this behavior again, I'm closing this since probably is fixed, feel free to reopen if not fixed on your side @gjabell

**Closed by ericdallo** 2021-02-07 23:11 UTC
