### ISSUE TITLE
clojure-lsp 2021.03.24-00.41.55 alreays rescan classpath jars upon earch restarts.

### ISSUE THREAD

**Issue by FongHou** [clojure-lsp/clojure-lsp#382] opened 2021-03-24 01:35 UTC
**Describe the bug**
Latest release clojure-lsp 2021.03.24-00.41.55 alreays rescanning classpath jars upon earch restarts.

**To Reproduce**
1. rm .lsp/sqlite.db
2. nvim a source file from a project. clojure-lsp scans project classpath. verify .lsp/sqlite.db created. tail -f /tmp/clojure-lsp.out shows first scan completed successfully.
3. exit nvim
4. nvim a source file again
5. observe high cpu more than 30 seconds, tail -f /tmp/clojure-lsp.<latest>.out shows
```
2021-03-24T01:23:39.102Z win-x1-laptop INFO [clojure-lsp.main:386] - Starting server...
2021-03-24T01:23:39.110Z win-x1-laptop INFO [clojure-lsp.nrepl:21] - ====== LSP nrepl server started on port 34021
2021-03-24T01:23:39.123Z win-x1-laptop INFO [clojure-lsp.main:288] - Initializing...
2021-03-24T01:23:43.082Z win-x1-laptop WARN [clojure-lsp.db:55] - Could not load db Invalid token: <list:
2021-03-24T01:23:49.814Z win-x1-laptop INFO [clojure-lsp.crawler:83] - Analyzing 147 paths with clj-kondo with batch size of 3 ...
2021-03-24T01:23:49.815Z win-x1-laptop INFO [clojure-lsp.crawler:89] - Analyzing 1/3 batch paths with clj-kondo...
2021-03-24T01:24:06.132Z win-x1-laptop INFO [clojure-lsp.crawler:89] - Analyzing 2/3 batch paths with clj-kondo...
2021-03-24T01:24:19.618Z win-x1-laptop INFO [clojure-lsp.crawler:89] - Analyzing 3/3 batch paths with clj-kondo...
```

**Expected behavior**
Rollback previous release. Step 5 completes the scan within a few seconds. tail -f /tmp/clojure-lsp.out shows only project sources are parsed. 

**Screenshots**

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
ADD HERE
</pre>
</details>

<details>
 <summary><b>Log - /tmp/clojure-lsp.*.out</b></summary>
<pre>
ADD HERE
</pre>
</details>

**User details (please complete the following information):**
 - OS: Windows 10 WLS2 running Ubuntu LTS
 - Editor: nvim + coc
 - Version: clojure-lsp 2021.03.24-00.41.55 clj-kondo 2021.03.22

**Additional context**

**Comment by ericdallo** [comment] 2021-03-24 01:48
Thanks!
What project did you test that? I could only reproduce it on clojure-lsp project, but it's a know issue, in my sample project I could not reproduce it

**Comment by FongHou** [comment] 2021-03-24 01:54
It seems a regression. The project doesn't have this issue with previous release.

**Comment by ericdallo** [comment] 2021-03-24 03:09
Yes, I agree it's an issue, I just wanted to confirm if it was a global issue affecting all issue of just the clojure-lsp project.

The issue seems to be happening because we are not correctly converting to a valid edn before persist with sqlite.
It seems the `:defined-by` key of clj-kondo analysis is returning `<list>`

**Comment by ericdallo** [comment] 2021-03-24 03:21
It seems to be a issue linting `clojure.spec.gen.alpha`: https://github.com/clojure/spec.alpha/blob/master/src/main/clojure/clojure/spec/gen/alpha.clj#L101-L111

Sample of a kondo analysis on that file
```clojure
{:end-row 134
:name-end-col 75
:name-end-row 134
:name-row 132
:ns clojure.spec.gen.alpha
:name large-integer
:defined-by <list: (lazy-prims any any-printable boolean bytes char char-alpha char-alphanumeric char-ascii double int keyword keyword-ns large-integer ratio simple-type simple-type-printable string string-ascii string-alphanumeric symbol symbol-ns uuid)>
:filename "clojure/spec/gen/alpha.clj"
:col 1
:name-col 1
:end-col 75
:row 132}
```

Not sure why it happens on clj-kondo c/c @borkdude

**Comment by FongHou** [comment] 2021-03-24 03:26
I'm not sure which jar in my project causes this. I thought it's [org.clojure/alpha.spec "0.2.177-SNAPSHOT"] as it's mentioned in the other issue, but removing it doesn't seem make a difference.

I don't see that strange '<list' in sqlite.db file though. Where did you find that?

```
 strings .lsp/sqlite.db | grep -e '<list'

 find .clj-kondo -name \*.json | xargs cat | grep '<list'

```

return nothing.

**Comment by ericdallo** [comment] 2021-03-24 03:26
I found on sqlite.db, try removing the sqlite.db and reanalyzing it with clojure-lsp, then you can repro

**Comment by FongHou** [comment] 2021-03-24 03:47
Confirmed. thank you for looking into it!

**Comment by FongHou** [comment] 2021-03-24 04:12
maybe something to do with this commit https://github.com/clj-kondo/clj-kondo/commit/2465976ec9e9529788c0eb1ba34eee3e2b83657d. Not sure why analyze-lazy-combinators was removed.

**Comment by borkdude** [comment] 2021-03-24 08:50
It was replaced by linting the call as `declare` because there was another macro in `sgen` exactly like this. 

See here: https://github.com/clj-kondo/clj-kondo/commit/2465976ec9e9529788c0eb1ba34eee3e2b83657d#diff-f591b825c81f488c7fa9426a07ba9dd30f948cc52e445be929d5fd8299bc7ddeR1573

It seems we are passing a raw node to `:defined-by` somewhere.

**Comment by borkdude** [comment] 2021-03-24 10:24
Fixed in https://github.com/clj-kondo/clj-kondo/issues/1231

**Comment by borkdude** [comment] 2021-03-24 10:57
I also added an extensive test in CI to ensure analysis data is readable as EDN.

**Comment by ericdallo** [comment] 2021-03-24 11:07
Thank you @borkdude !

I'll bump and test it

**Comment by ericdallo** [comment] 2021-03-24 12:21
it fixes the issue, thank you for the quick help!

**Closed by ericdallo** 2021-03-24 12:21 UTC
Labels: bug
