### ISSUE TITLE
jump to definition from clojure to java and beyond

### ISSUE THREAD

**Issue by rgkirch** [clojure-lsp/clojure-lsp#1187] opened 2022-08-11 21:53 UTC
I'm currently able to jump from clojure code to a definition in java but I'm not able to further jump to other definitions in java.

When clojure-lsp jumps from clojure to java I'd like a java extension take over and facilitate further java code navigation. In vscode this would be the [redhat extension](https://marketplace.visualstudio.com/items?itemName=redhat.java). Clojure-lsp can do this by providing the pom.xml and all the java sources instead of only the one java source file.

https://clojurians-log.clojureverse.org/lsp/2022-07-28/1659050935.316579
https://clojurians.slack.com/archives/CPABC1H61/p1659050935316579?thread_ts=1659043790.744119&cid=CPABC1H61

**Comment by ericdallo** [comment] 2022-08-12 16:05
Thanks for the report, as mentioned in the thread, if we could create a project structure with pom.xml that would be a valid fix to me, the issue is that we would need to decompile the whole jar async when source not available

**Comment by ericdallo** [comment] 2022-09-04 18:18
Fixed on https://github.com/clojure-lsp/clojure-lsp/commit/cd37ffe6e829acad60e4797fb7e81aa6d21693a9, LMK if any issues

**Closed by ericdallo** 2022-09-04 18:18 UTC
Labels: enhancement

**Comment by rgkirch** [comment] 2022-09-04 20:28
Thank you so much; I'm looking forward to using this!

**Comment by ericdallo** [comment] 2022-09-04 22:24
@rgkirch you can already give it a try with a nightly build

**Comment by rgkirch** [comment] 2022-09-12 17:58
macos
```
curl -O https://raw.githubusercontent.com/clojure-lsp/clojure-lsp/master/install
chmod a+x install
sudo ./install --version nightly

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4014  100  4014    0     0  13224      0 --:--:-- --:--:-- --:--:-- 13469
Password:
Downloading https://github.com/clojure-lsp/clojure-lsp-dev-builds/releases/latest/download/clojure-lsp-native-macos-amd64.zip to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.LVEydDbT
Successfully installed clojure-lsp in /usr/local/bin
```
```
clojure-lsp --version
clojure-lsp 2022.09.12-13.52.05-nightly
clj-kondo 2022.09.08
```
in vscodium, I get a notification in the bottom right that says
```
LSP classpath lookup failed when running `lein with-profile +test,+dev classpath`. Some features may not work properly if ignored. Error: Cannot run program "lein" (in directory "/Users/rkirchofer/clj-scratch"): error=2, No such file or directory Choose an option:
```

calva says
```
Welcome to Calva. Happy Clojure and ClojureScript coding! ❤️

Please check these resources out:
  Calva Documentation: https://calva.io/
  #calva at the Clojurians Slack: https://clojurians.slack.com/messages/calva/
  Bug reports: https://github.com/BetterThanTomorrow/calva/issues

If you like Calva, please consider how you can contribute: https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute

Calva is utilizing cider-nrepl and clojure-lsp to create this VS Code experience.
  nREPL dependencies configured:
    nrepl: 1.0.0
    cider-nrepl: 0.28.5
    cider/piggieback: 0.5.3
  clojure-lsp path configured: /usr/local/bin/clojure-lsp

If you are new to Calva, please consider starting with the command:
  **Calva: Fire up the Getting Started REPL**
  https://calva.io/getting-started/

(See `showCalvaSaysOnStart` in Settings to control the auto-showing of this message panel.)
VIM Extension detected. Please read: https://calva.io/vim/ now and then.
```
This is likely unrelated to the feature request.

**Comment by ericdallo** [comment] 2022-09-12 18:11
@rgkirch this is calva issue, where it's not using the same PATH env from your terminal where it has clojure-lsp installed
