### ISSUE TITLE
Rename symbol does not change symbols in map destructuring form with `:or` directive

### ISSUE THREAD

**Issue by DeLaGuardo** [clojure-lsp/clojure-lsp#1562] opened 2023-05-04 08:41 UTC
**Is your feature request related to a problem? Please describe.**
Consider this block:

```clojure
(let [{:keys [foo] :or {foo 42}} {:foo 0}]
  (inc foo))
```

When I use the action rename symbol `foo` it works mostly as expected, except it doesn't change the symbol inside `:or {foo 42}` destructuring form. So, after renaming `foo` to `bar` the same snippet will look like this:

```clojure
(let [{:keys [bar] :or {foo 42}} {:foo 0}]
  (inc bar))
```

In some huge bindings blocks that might end up with tricky hidden bug.

**Describe the solution you'd like**
Because I expect rename symbol to alter all occurrences of the symbol `foo` it would be great if the action will change "defaults" as well.

**Describe alternatives you've considered**
Some sort of interactive mode questioning how to proceed in case clojure-lsp detects that rename suppose to target "defaults".

**Comment by ericdallo** [comment] 2023-05-04 13:08
Good catch, we should fix it, the issue is that we don't have any analysis for the `foo` inside the `:or`, so we would need probably a change in clj-kondo first to include those analysis so LSP can query and know what are them.

@borkdude I'd say those are locals as well but with some flag saying they come from :or, WDYT?

**Comment by borkdude** [comment] 2023-05-04 13:10
I'd say the `foo` in `:or` is a local usage. Issue (+ PR) welcome.

**Comment by ericdallo** [comment] 2023-05-04 13:21
@DeLaGuardo feel free to open a issue in clj-kondo about that, otherwise I should do it in some days

**Comment by DeLaGuardo** [comment] 2023-05-05 13:45
Was unable to submit one yesterday due to github troubles :)
https://github.com/clj-kondo/clj-kondo/issues/2068

**Comment by ericdallo** [comment] 2023-05-27 15:33
Fixed on nightly/master, should be available on the next release

**Closed** 2023-05-27 15:32 UTC
Labels: enhancement
