### ISSUE TITLE
Publishing diagnostics at startup fills up the channel

### ISSUE THREAD

**Issue by lassemaatta** [clojure-lsp/clojure-lsp#1153] opened 2022-07-26 04:36 UTC
**Describe the bug**

I noticed an exception in the logs when testing the latest `clojure-lsp` binary. Not sure how this affects the editor, perhaps some of the diagnostics get discarded. I don't think I've seen this before.

**To Reproduce**
1. Open a large project (thousands of namespaces) in an editor
2. Look at the logs
3. Notice hundreds of "Publishing N diagnostics for file..." messages
4. See stacktrace

**Expected behavior**

No errors should occur. All diagnostics should be reported.

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
2022-07-26T04:21:37.250Z  ERROR [taoensso.timbre:828] - Uncaught exception on thread: async-dispatch-2
com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine    PosixJavaThreads.java:  194
            com.oracle.svm.core.thread.JavaThreads.threadStartRoutine         JavaThreads.java:  597
                                                 java.lang.Thread.run              Thread.java:  829
                                                                  ...                               
   clojure.core.async.impl.concurrent/counted-thread-factory/reify/fn           concurrent.clj:   29
                   java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  628
                    java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1128
                                                                  ...                               
                                   clojure-lsp.handlers/initialize/fn             handlers.clj:  105
         clojure.core.async.impl.ioc-macros/run-state-machine-wrapped           ioc_macros.clj:  982
                 clojure.core.async.impl.ioc-macros/run-state-machine           ioc_macros.clj:  978
             clojure-lsp.handlers/initialize/fn/state-machine--auto--             handlers.clj:  105
          clojure-lsp.handlers/initialize/fn/state-machine--auto--/fn             handlers.clj:  106
             clojure-lsp.feature.diagnostics/publish-all-diagnostics!          diagnostics.clj:  165
            clojure-lsp.feature.diagnostics/sync-publish-diagnostics!          diagnostics.clj:  145
                                              clojure.core.async/put!                async.clj:  199
              clojure.core.async.impl.channels.ManyToManyChannel/put!             channels.clj:  156
java.lang.AssertionError: Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.
                          (< (.size puts) impl/MAX-QUEUE-SIZE)
</pre>
</details>

**User details (please complete the following information):**
 - OS: Arch Linux
 - Editor emacs
 - Version: `clojure-lsp 2022.07.24-18.25.43` + `clj-kondo 2022.06.23-SNAPSHOT`

**Comment by ericdallo** [comment] 2022-07-26 10:47
Thank you for the report, this is something that always happened but we didn't understand why or how to fix, with @mainej's PR #1117 we should fix those soon.

**Comment by ericdallo** [comment] 2022-08-10 00:07
@lassemaatta this should be fixed on master, please re-open if the problem persists on nightly build/next release

**Comment by lassemaatta** [comment] 2022-08-12 10:09
I tried the latest nightly and the issue still remains

<details>
<pre>2022-08-12T10:03:27.652Z  INFO [clojure-lsp.dep-graph:300] - :maintain-dep-graph 0ms
2022-08-12T10:03:27.652Z  INFO [clojure-lsp.feature.java-interop:256] - [Java] JDK source cached loaded successfully.
2022-08-12T10:03:27.666Z  WARN [clojure-lsp.kondo:298] - Non-fatal error from clj-kondo: No configs copied.

2022-08-12T10:03:27.667Z  INFO [clojure-lsp.dep-graph:300] - :maintain-dep-graph 0ms
2022-08-12T10:03:27.667Z  INFO [clojure-lsp.handlers:116] - :did-open 45ms
2022-08-12T10:03:27.668Z  INFO [clojure-lsp.server:147] - :refreshing-test-tree 0ms
2022-08-12T10:03:27.795Z  INFO [clojure-lsp.handlers:?] - :code-lens 0ms
2022-08-12T10:03:27.835Z  ERROR [taoensso.timbre:828] - Uncaught exception on thread: async-thread-macro-8
com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine  PosixPlatformThreads.java:  202
            com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine       PlatformThreads.java:  705
                                                     java.lang.Thread.run                Thread.java:  829
                       java.util.concurrent.ThreadPoolExecutor$Worker.run    ThreadPoolExecutor.java:  628
                        java.util.concurrent.ThreadPoolExecutor.runWorker    ThreadPoolExecutor.java: 1128
                                                                      ...                                 
                                        clojure.core.async/thread-call/fn                  async.clj:  484
                                       clojure-lsp.handlers/initialize/fn               handlers.clj:   99
                 clojure-lsp.feature.diagnostics/publish-all-diagnostics!            diagnostics.clj:  165
                clojure-lsp.feature.diagnostics/sync-publish-diagnostics!            diagnostics.clj:  145
                                                  clojure.core.async/put!                  async.clj:  199
                  clojure.core.async.impl.channels.ManyToManyChannel/put!               channels.clj:  156
java.lang.AssertionError: Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.
                          (< (.size puts) impl/MAX-QUEUE-SIZE)
</pre>
</details>

**Comment by ericdallo** [comment] 2022-08-12 15:25
FYI @mainej

**Comment by mainej** [comment] 2022-08-15 02:30
I'm re-opening this issue. I have an idea about how to fix it, but since I can't reproduce the problem locally, I might need your help @lassemaatta to verify my fix.

**Closed** 2022-08-16 19:32 UTC
Labels: bug, editor

**Comment by mainej** [comment] 2022-08-17 01:24
@lassemaatta when you have a chance, will you double check that [this build](https://clojurians.slack.com/archives/C032YH7P0R2/p1660679118165279) (or later) fixes this bug?

**Comment by lassemaatta** [comment] 2022-08-17 03:16
Sure, no problem. I'll report back once I've tested it.

**Comment by lassemaatta** [comment] 2022-08-17 04:04
@mainej Good news, with the latest nightly build the exception no longer occurs :tada: Grepping the logs shows that it published diagnostics for about 3k files. Thanks for fixing this!

**Comment by mainej** [comment] 2022-08-17 15:41
That's great @lassemaatta! We've had this bug for a long time, in different forms, with several attempts at fixing it. I'm really relieved this attempt seems to be working.

This was definitely a case where understanding the bug took much more effort than fixing it. You can read a write up, if you're interested, over in #1196.
