### ISSUE TITLE
Major slow down on recent versions

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#417] opened 2021-05-04 18:53 UTC
**Describe the bug**
did-change is now taking ~1-2 seconds to process whereas it was at ~2ms before

From 2bb8fc8
2021-05-04T18:48:56.170Z MacBook-Pro.local DEBUG [clojure-lsp.main:?] - :didChange 1389ms
From 034fdd0
2021-05-04T18:50:35.397Z MacBook-Pro.local DEBUG [clojure-lsp.main:?] - :didChange 0ms

Anything consistently over ~30ms should be considered too slow.

**Comment by ericdallo** [comment] 2021-05-04 20:15
Oh, odd, I'll take a look soon!

**Comment by ericdallo** [comment] 2021-05-04 20:17
@snoe that is a 1-month range, could you try other releases as well to try to find the offense commit?

**Comment by ericdallo** [comment] 2021-05-04 20:40
@snoe I think I found what caused that increase, but I don't think it's really a slow down: https://github.com/clojure-lsp/clojure-lsp/commit/857bdc186e5585771c3b50b2c444065fb2b2e018

I made this after realizing a issue with semantic tokens where we were handling the semantic tokens request after the didChange but since we was processing the changes async that could cause semantic tokens to get outdated changes.

So, maybe the issue is that we stopped handling didChange for `:full` async to handle it sync

**Comment by snoe** [comment] 2021-05-04 22:08
@ericdallo 

So I think we should have a clearer delineation on what should be "immediate feedback" vs "later feedback". That should allow us to scope what work can be done on-change. It's not really about sync v async but how long it takes from typing something to getting feedback about that thing.

I think analyzing the changed the file and diagnostics needs to be done as quickly as possible - within that 30ms timeframe. Otherwise as a user types their editor takes seconds to catch up. That quick feedback is very important and laggy updates for those things are confusing and frustrating. Watch how diagnostics are slow to come in:
![slow-feedback](https://user-images.githubusercontent.com/105012/117075702-80ecd580-acf2-11eb-97f9-ada4610ee83f.gif)

Analyzing and diagnosing other, dependent files or updating things that aren't immediately around the cursor, or less important to know as you type can be done more slowly, in batches, and debounced if necessary.

**Comment by ericdallo** [comment] 2021-05-04 22:15
It makes sense! but it seems that we are already doing this way after https://github.com/clojure-lsp/clojure-lsp/commit/857bdc186e5585771c3b50b2c444065fb2b2e018, but sync, without debouncing (since for :full text-sync the client send text changes as batch, so we don't need debouncing)

So I imagine what changed was only the log, that now really logs the time spent during did-changes analysis, right?

**Comment by snoe** [comment] 2021-05-05 19:03
Eh, maybe it was still slow at that commit, without measuring it seems more responsive to me but hard to tell objectively.

Definitely when we first released the kondo changes the time was way down so maybe it's been from other changes between then but the feedback speed should be addressed regardless of what caused it.

**Comment by ericdallo** [comment] 2021-05-05 19:40
Yeah, I'll take a look, but LMK if you find some closer version which looks faster for you

**Comment by ericdallo** [comment] 2021-05-15 01:34
Fixed on latest release

**Closed by ericdallo** 2021-05-15 01:34 UTC
Labels: bug
