### ISSUE TITLE
Support jump to definition for quoted symbols

### ISSUE THREAD

**Issue by mk** [clojure-lsp/clojure-lsp#1403] opened 2022-12-03 20:39 UTC
**Is your feature request related to a problem?**

I'd like to be able to jump to the definition of a quoted symbol, e.g.:
```clojure
;; quote
(requiring-resolve 'clojure.set/rename-keys)

;; alias + sharp quote
(alias 's 'clojure.set)
(requiring-resolve `s/rename-keys)

;; alias + normal quote
(alias 's 'clojure.set)
(requiring-resolve 's/rename-keys)
```
(the last should probably try to resolve `'s/rename-keys` first and only if that fails fall back to trying `'clojure.set/rename-keys`

**Additional context**
Besides the requiring-resolve examples above, this would also be great for render-fns in Clerk e.g. https://github.com/nextjournal/clerk/blob/edd0c2fc22bd0207cc8d3762f00f239ce63ee87f/src/nextjournal/clerk/viewer.cljc#L733

We've previously discussed this on slack: https://clojurians.slack.com/archives/CPABC1H61/p1668186899410569

In that slack thread @ericdallo pointed out the current resolution code:

https://github.com/clojure-lsp/clojure-lsp/blob/f82e9e71ddd5780e766a3475515612982ad323a0/lib/src/clojure_lsp/queries.clj#L502-L506

**Comment by ericdallo** [comment] 2022-12-04 13:14
@mk rechecking this, it seems it'd help a lot if clj-kondo could provide additional __symbol analysis__, otherwise we would need to change some core code to not rely only on kondo analysis but do our custom parsing which is something I'd like to avoid for maintainability reasons.

we used to have issues like that in the past like no keyword analysis, java analysis, and adding in kondo helped a lot of things keep simple, so a flag to analyze symbols as well sounds like something that would help not only 1 or 2 features to work with symbols but probably all clojure-lsp features since most of them rely on kondo analysis.

WDYT @borkdude? Since it would be a new context flag or something, it looks to me good enough to be kondo that provides that info, also it's something that makes sense to me to kondo provide for a project

**Comment by borkdude** [comment] 2022-12-04 13:49
@ericdallo clj-kondo needs context in which to resolve a symbol. e.g. if a symbol is `a/foo` it needs to know the aliases and imports of that namespace. Given that lsp already has this information from prior calls to clj-kondo, but clj-kondo doesn't have this context, wouldn't it be more evident to do this in lsp? I think you would just have to check the aliases and imports to get the fully qualified name, or am I wrong?

**Comment by ericdallo** [comment] 2022-12-04 14:06
my point is that ATM clojure-lsp completly relies on kondo analysis and do not parse code with rewrite-clj for queries like that, which would imply some changes on how lsp handle things.

>  it needs to know the aliases and imports of that namespace.

doesn't clj-kondo do that already for all other analysis? example: `::a/foo` it knows that `a` alias points to a namespace:
```clojure
{:ns clojure.pprint
 :name "foo"
 :auto-resolved true
 :alias a
 :from clojure-lsp.handlers
 :bucket :keyword-usages
 ...}
```

**Comment by ericdallo** [comment] 2022-12-04 14:08
it's like ask to implement support for aliased keywords for example, we could parse things but would make things a lot harder and since clj-kondo is the tool that has the code analysis, I see having the symbol analysis there could benefit both clojure-lsp and all clients of clj-kondo that uses analysis and are interested on symbol analysis as well

**Comment by borkdude** [comment] 2022-12-04 14:09
OK, let me ask the question differently. What is the clj-kondo API you would propose, including the arguments and return value? Then I think my previous point will become more obvious.

**Comment by ericdallo** [comment] 2022-12-04 14:14
I thought about something like:
```clojure
(clj-kondo.core/run
  {:arglists true
   :locals true
   :keywords true
   :symbols true ;; new flag here
   :protocol-impls true
   :java-class-definitions true
   :instance-invocations true
   ...})
;; output

{:symbols [{:filename "..."
            :name "foo"
            :alias "a"
            :ns "my.a"
            :row ...}]
 ...}
```

**Comment by borkdude** [comment] 2022-12-04 14:23
Oh, you mean as an extra "bucket" in the analysis, sure. I thought you wanted to ask clj-kondo about a symbol after you had already analyzed, but this makes sense.

Let's get into some details.

If we have this:

``` clojure
(ns foo (:require [clojure.set :as set]))
'set/foobar ;; 1
'clojure.set/foobar ;; 2
`set/foobar ;; 3
`clojure.set/foobar ;; 4
set/union ;; 5 (var-usage)
```

1 and 2 bear no relation to `clojure.set` even if the namespace or alias is the same: a quoted symbol is just plain data that doesn't need the namespace `clojure.set` to exist. But in the case of syntax-quote (3 and 4) these symbols are _already_ part of `:var-usages`. In syntax code there is a real reference to namespaces and aliases.

For code analysis it makes no sense to emit analysis for 1 and 2, but for navigation purposes it might be convenient (e.g. in symbols passed to `requiring-resolve`).

What kind of output do you expect for 1 and 2? Do you also want to see 3 and 4 considering that the output is already in var-usages? Should we move the var-usages to symbols?

**Comment by borkdude** [comment] 2022-12-04 14:28
Tbh, I think just resolving the symbol with the data you already have from clj-kondo is the least amount of work for this feature, assuming that you can get the symbol at the cursor.

Given 1: look for alias set, then replace the namespace, then navigate like you always do.
Given 2: similar

**Comment by borkdude** [comment] 2022-12-04 14:49
> as we would need to introduce a new concept of parsing the code before querying just for that case

Keep in mind that clj-kondo now has to introduce a new category of analysis just for this case. This is the first use case that requires adding information about resolved symbols that are not really resolved.

Navigating to a rewrite-clj node at a certain location is trivial. Looking inside the clj-kondo bucket using the information from the symbol is also trivial.

**Comment by mk** [comment] 2022-12-04 14:49
@borkdude I don't see a different between syntax quote and regular quote (2 and 3) in case you're using a fully qualified or non-existent ns:

```clojure
(= 'clojure.set/foobar
   `clojure.set/foobar) ;;=> true
(= 'clojure.set-non-existent/foobar
   `clojure.set-non-existent/foobar) ;;=> true
```

Curious to learn why clj-kondo treats them differently for analysis.

**Comment by borkdude** [comment] 2022-12-04 14:52
@mk Because clojure does use the state of the required namespaces and aliases to resolve those symbols, it is indirectly a namespace/var reference, if found. If nothing matches, then it defaults to whatever the user wrote.

**Comment by borkdude** [comment] 2022-12-04 14:54
Let me think about how we could add analysis as if in syntax-quote, but for normal quote. It might not always be desirable to have this analysis by default. As I'm in Berlin next week, perhaps we could hack on it together @mk

**Comment by ericdallo** [comment] 2022-12-04 14:55
I see a new bucket category as easier to maintain as clj-kondo has already different buckets concept, in lsp this would be a new kind of find-element/references/definition and other features category which differs a lot from how lsp query elements, which is only on analysis.

For a mid/long term solution, this new clj-kondo analysis bucket looks to me the best, would require fewer changes on lsp and other analysis clients could use that info as well.

**Comment by borkdude** [comment] 2022-12-04 14:57
I think the issue is more that clerk wants to treat the quoted `'(fn [_] (v/whatever))` form as if it was written like: 

``` clojure
`(fn [_] (v/whatever))
```

Perhaps this is better solved using a clj-kondo hook which rewrites the quote to a backtick (which I'm not sure is already possible).

**Comment by borkdude** [comment] 2022-12-04 14:59
The same should be possible for `requiring-resolve`. Perhaps a clj-kondo option to configure this kind of behavior per function makes more sense since it's just not correct to emit `nextjournal.clerk.viewers/whatever` for a random `v/whatever` symbol.

**Comment by ericdallo** [comment] 2022-12-04 15:02
Maybe we could start simpler? I can't understand a user case for ``(fn [_] (v/whatever))` really

**Comment by borkdude** [comment] 2022-12-04 15:24
Note that the behavior for clj-kondo with syntax quote is that when you're using an alias that is unknown, it will hint that you have forgotten something:

<img width="645" alt="Screenshot 2022-12-04 at 16 21 56" src="https://user-images.githubusercontent.com/284934/205499181-d50fa5bf-6354-45f1-8a3c-d31eaac5b0f7.png">

This may or may not be desirable for clerk viewer functions but with requiring-resolve I think it's not the right thing to do.
Hence we have found one undesirable case when regular quote is treated as normal quote.

**Comment by borkdude** [comment] 2022-12-04 15:30
Clearly this issue needs more hammock time.

**Comment by borkdude** [comment] 2022-12-04 15:32
@ericdallo Could you explain to me what exactly the problem is with parsing the code with rewrite-clj to get the symbol under the cursor? This is really the only thing you need to do to make this work in clojure-lsp I think. You're already using rewrite-clj for refactoring, so what exactly is stopping you?

**Comment by borkdude** [comment] 2022-12-04 15:41
I understand that you don't want to parse the file ahead of time, because of performance reasons, but this can be done lazily as a fallback when no other navigation has been found, which should be fast enough.

**Comment by ericdallo** [comment] 2022-12-04 15:43
All logic on clojure-lsp regarding finding definition/references and other things are [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/src/clojure_lsp/queries.clj), you can see we only rely on clj-kondo analysis. 

First, we would need to always parse the user file code with rewrite-clj for every action like definition/references since we don't know if it's a symbol or not the cursor, which would probably cause performance issues for large buffers, since we call definition and references for each user code change to recalculate lens and lots of other things, that's why queries need to be fast and they are since they rely on kondo analysis map only ATM.
Then, we would need pass that rewrite node to queries which would check if it's a symbol and then do its custom parsing to then use analysis as you mentioned above.

So, the biggest concern is blast radius + performance, since we would need to introduce a new parsing only for this specific feature which seems too much IMO for lsp and if we think about caching the zloc that could cause outdated and not consistent queries, seems to only hide that this kind of operation maybe should not belong on lsp side.

As I mentioned, I don't see treating symbols that much different than other things like keywords on kondo side.

**Comment by borkdude** [comment] 2022-12-04 15:53
You can even do this without rewrite-clj: given the location of the cursor, go into the file, read the surrounding form - if it does not start with a quote, we ignore it, and the navigation has failed. This will be less than a millisecond.

**Comment by ericdallo** [comment] 2022-12-04 16:00
Yeah, those things would probably work but add weird layers of querying IMO, like fallback to parse code if no analysis is found, things that would add complexity layers only for that case, and we would need to think about performance, which walk to the node is not the concern, but parsing a whole file string to a node is as we already had performance issues like that in the past.

Kondo is our base for analysis, if we start to have our own custom analysis build it would become what it was before we use kondo, our own custom analysis which was pretty complex to maintain IMO.

I can't understand why you think this does not belong on clj-kondo, we already have the same for keywords and similar analysis

**Comment by borkdude** [comment] 2022-12-04 16:05
> but parsing a whole file string to a node is as we already had performance issues like that in the past

I just gave you another solution which should work below a millisecond.

> I can't understand why you think this does not belong on clj-kondo, we already have the same for keywords and similar analysis

Because it adds very little value to clj-kondo right now (nobody has ever requested analysis for quoted symbols) and because the existing analysis you have from clj-kondo is sufficient, when you have the symbol (which is not hard to get!).

If there would be more than just this use case for quoted symbols, I'd be happy to add them, but I don't see those right now.

**Comment by ericdallo** [comment] 2022-12-04 16:11
> I just gave you another solution which should work below a millisecond.

That's something that I would really like to avoid, custom parsing code not using rewrite-clj, which seems even harder to maintain.

> Because it adds very little value to clj-kondo right now

Weren't all other kondo analysis features like `:keywords`, `protocol-impls`, `java-class-definitions`, `instance-invocations`, `local-usages` added with lsp being the first client? I see clj-kondo as a robust analysis tool and I think those features help a lot with that.

**Comment by borkdude** [comment] 2022-12-04 16:31
Yes, those things were added for lsp as the first client, and I'm happy to support this client :) But also, those kinds of analysis are not hard to imagine a use case for outside of lsp. For quoted symbols it's not yet so evident to me what the analysis should look like. What clj-kondo could do is add a quoted-symbols bucket (as unquoted symbols refer to vars, usually) and then it's up to the user how to interpret that:

```
:symbol v/my-viewer
:row 1
:col 2
:file "foo.clj"
```

But then the question is how far to go with this, as e.g. symbols from `(require '[foobar.baz :as baz])` might not be so interesting and useful (there are two quoted symbols in there which already have a clear meaning in clj-kondo).

**Comment by ericdallo** [comment] 2022-12-04 19:06
@borkdude I think for clojure-lsp have a element with the literal symbol would already help a lot and make things way easier for clojure-lsp, example:

```clojure
(ns user (:require [foo :as f]))
'foo/bar
'f/bar
```
```clojure
[{:symbol 'foo/bar
  :file ...
  :row ...}
 {:symbol 'f/bar
  :file ...
  :row ...}]
```

Since would avoid clojure-lsp need to parse any code and with that we could read the `symbol` field and do other subqueries as checking if the symbol ns is a alias or just a full ns, WDYT? it'd be easier/simpler to provide that on clj-kondo right?

**Comment by borkdude** [comment] 2022-12-04 19:38
@ericdallo It would not be so hard to provide this from the clj-kondo side. My suspicion is that only namespaced symbols would be interesting since those potentially point to vars and this would aid navigation. 

- We could skip things like `baz` in `(require '[foo.bar :refer [baz])` 
- We include `v/viewer in `'(fn [] (v/viewer 1 2 3))`

Right @mk? Could you confirm that unnamespaced symbols aren't interesting to have analysis on?

**Comment by mk** [comment] 2022-12-04 19:54
> Right @mk? Could you confirm that unnamespaced symbols aren't interesting to have analysis on?

In the case of Clerk viewer functions, I'd also be interested in being able to jump to the definition of unnamespaced symbols but if we can get namespaced symbols working that would already be a great improvement.

**Comment by borkdude** [comment] 2022-12-04 19:58
@mk How could a static analyzer know the definition of an unnamespaced symbol? Need examples.

**Comment by mk** [comment] 2022-12-04 20:10
@borkdude in the case of Clerk viewer functions, it will be regular Clojure code, albeit in a quoted form, so resolution would be identical to regular (unquoted) code. An example would be https://github.com/nextjournal/clerk/blob/49dd16e2800d54f0a3e0edf03fd2ef1213720ee6/src/nextjournal/clerk/viewer.cljc#L527-L535

**Comment by borkdude** [comment] 2022-12-04 20:39
So you want linting / analysis to behave as if the quote wasn't there at all. That is probably possible but not without some extra help for static analysis, e.g. by surrounding it with a macro like:

```
(require '[nextjournal.clerk :refer [render-fn]])

(render-fn (fn [] (v/viewer 1 2 3)))
```

and this macro would then just expand into a quoted form.

**Comment by mk** [comment] 2022-12-04 20:55
> That is probably possible but not without some extra help (for static analysis), e.g. by surrounding it with a macro like:

It used to be a macro in the early days but then we went with a quoted form to make it clear to the user that it's something different than e.g. the `:transform-fn` which runs on the JVM. Think a macro like you're suggesting will also lead to other issues e.g. with `js/,,,` forms.

**Comment by borkdude** [comment] 2022-12-04 21:06
Why would that give issues?

```
user=> (defmacro cq [body] (list 'quote body))
#'user/cq
user=>
user=> (defmacro rf [body] (list 'quote body))
#'user/rf
user=> (rf '(fn [] (js/foobar)))
(quote (fn [] (js/foobar)))
```

Using this type of macro will also give you the opportunity to fine-tune linting, e.g. suppress certain or are unresolved symbols, while still being able to navigate locals, etc.

**Comment by mk** [comment] 2022-12-04 21:09
@borkdude does it have to be a macro or can that also be done with a regular function (that takes a quoted form) as an argument? Or even the `:render-fn` key inside a map?

**Comment by borkdude** [comment] 2022-12-04 21:12
Please read the original post here... https://github.com/nextjournal/clerk/issues/101
It can be a function or a macro, but a macro will probably be easier since you can configure it directly without writing a hook for it. So instead of `'(fn [])` you write `(rf (fn []))` - the `rf` wrapper replaces the quote.

**Comment by borkdude** [comment] 2022-12-04 21:15
Note that this macro can live outside of clerk if you're concerned about adding it right now, so we can freely experiment with how it feels.

**Comment by borkdude** [comment] 2022-12-04 21:26
It can be a function, but this requires a hook which then removes the quote, expands into another function call, which can then be fine-tuned for linting. I can make demos for both tomorrow.

**Comment by borkdude** [comment] 2022-12-05 12:19
@ericdallo I made a PR here https://github.com/clojure-lsp/clojure-lsp/pull/1405#issuecomment-1337248679 to show how we can enable navigation in clojure-lsp for vars that are mentioned in quoted clojurescript expressions, given the right clj-kondo hook. That hook is in a branch of clerk over here:

https://github.com/nextjournal/clerk/tree/jump-to-definition

**Comment by borkdude** [comment] 2022-12-05 12:19
Demo:

![clj- cljs-nav](https://user-images.githubusercontent.com/284934/205635734-64d2313b-3fb1-42e0-b3f2-6b48dc8c567c.gif)

**Comment by ericdallo** [comment] 2022-12-05 12:29
@borkdude I added a comment on the PR, TBH I don't understand why/how it's possible to go from clj -> cljs code, AFAIK it was possible only cljc -> cljs.

**Comment by ericdallo** [comment] 2023-01-12 17:28
@borkdude I think this is now working given #1447 right?

**Comment by borkdude** [comment] 2023-01-12 17:45
Yes. Can you also bump clj-kondo even more than I did in my PR? It has some more stuff

**Comment by ericdallo** [comment] 2023-01-14 13:08
Done @borkdude

**Closed** 2023-01-14 13:08 UTC
Labels: enhancement
