### ISSUE TITLE
Weird highlighting of case, cond, cond-> and cond->> 

### ISSUE THREAD

**Issue by PEZ** [clojure-lsp/clojure-lsp#385] opened 2021-03-27 08:36 UTC
**Describe the bug**

In VS Code/Calva I get this weird and jarring highlighting of  the threaded expression of `cond->` and `cond->>` forms. It seems to not always happen, but right now I fail to reproduce a case where it does not happen. It looks like so if the expression is a map:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/30010/112714768-52523280-8edc-11eb-87db-f038bba959ae.png">

**To Reproduce**

1. Put this into an empty `.clj` file:
   ```clojure
    (cond-> {:foo :bar
             :baz :gaz})    ```
2. Place the cursor in one of the keys or values
3. The map is highlighted.

**Expected behavior**

The map should not be highlighted.

**Screenshots**

It looks even more striking with a light theme: 😄 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/30010/112715044-32237300-8ede-11eb-9d03-c8afa50d2230.png">


<!-- Fill the template below with the request/response logs between client and clojure-lsp. -->

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
ADD HERE
</pre>
</details>

Don't know where this log is. 😄 

<!-- Fill the template below with the content of the `/tmp/clojure-lsp.*.out` most recent/relevant to this bug if any exceptions/relevant logs -->

<details>
 <summary><b>Log - /tmp/clojure-lsp.*.out</b></summary>
<pre>
ADD HERE
</pre>
</details>

Last thing logged in the only clojure-lsp.out file I find was five days ago.

**User details (please complete the following information):**
 - OS: MacOS Big Sur
 - Editor: VSCode (Calva)
 - Version: `'2021.03.24-00.41.55'` (binary)

**Additional context**
I think this is semi-new. Saw it the first time some week ago, but it could be quite a bit older than that anyway.

**Comment by ericdallo** [comment] 2021-03-27 13:32
Thanks for the report!
I could reproduce right now with the map on cond-> indeed.
The issue seems to be on clj-kondo side, for some it return the position of the whole form for maps, vectors, functions etc.

For a code:
```clojure
(cond-> {:a 1
         :b 2})
```
It returns: 
```clojure
{:end-row 10,
  :name-end-col 15,
  :name-end-row 10,
  :name-row 9,
  :name G__30427,
  :filename ...,
  :str "G__30427",
  :col 9,
  :id 1,
  :name-col 9,
  :end-col 15,
  :bucket :locals,
  :row 9}
```
Where the `name-*` is not correct I think.

c/c @borkdude

**Comment by borkdude** [comment] 2021-03-27 13:39
@ericdallo You might be able to see what is causing unexpected behavior here:

https://github.com/clj-kondo/clj-kondo/blob/76143d350946c18cd3ffc425b35aa01a6c78561d/src/clj_kondo/impl/macroexpand.clj#L52

**Comment by ericdallo** [comment] 2021-03-27 16:00
@borkdude I made a change and it fixes the issue:
I changed [this line](https://github.com/clj-kondo/clj-kondo/blob/76143d350946c18cd3ffc425b35aa01a6c78561d/src/clj_kondo/impl/macroexpand.clj#L59-L60) to:
```clojure
        g (token-node (gensym))
```
But I'm not sure if this could affect anything or if it's the correct approach.

**Comment by ericdallo** [comment] 2021-03-27 16:03
It fails a test though: https://github.com/clj-kondo/clj-kondo/blob/76143d350946c18cd3ffc425b35aa01a6c78561d/test/clj_kondo/main_test.clj#L2418-L2419

**Comment by borkdude** [comment] 2021-03-27 16:05
This should keep working:

<img width="310" alt="Screenshot 2021-03-27 at 17 04 45" src="https://user-images.githubusercontent.com/284934/112726597-9108dc80-8f1e-11eb-9cb0-77660860d09c.png">

**Comment by borkdude** [comment] 2021-03-27 16:06
I don't really care about the exact position though, as long as it has a (sane) position.

**Comment by ericdallo** [comment] 2021-03-27 16:06
Yes, but I have no idea why that change affect that 😅

**Comment by borkdude** [comment] 2021-03-27 16:06
Because the binding doesn't have a location anymore.

**Comment by ericdallo** [comment] 2021-03-27 16:08
Yeah, I think we could think in some way of just remove the generate symbol from analysis? this way the linter keeps working and we remove this generated symbol that does not seem to make sense since is not a real code, but a generated one?

**Comment by borkdude** [comment] 2021-03-27 16:11
Makes sense, we can add a metadata key to it exclude it from locals analysis output.

**Comment by ericdallo** [comment] 2021-03-27 16:12
Alright, I'll try to do that :)

**Comment by borkdude** [comment] 2021-03-27 16:16
@ericdallo I already use the key `(:clj-kondo.impl/generated expr)` in several places to skip certain things, maybe we could re-use that. It's just an added key on the node itself.

**Comment by ericdallo** [comment] 2021-03-27 19:43
It should be fixed on next release @PEZ :)
Thanks for the help @borkdude

**Closed** 2021-03-27 19:42 UTC
Labels: bug
