### ISSUE TITLE
`clojure-lsp/unused-public-var` ignores config from ns form

### ISSUE THREAD

**Issue by skylize** [clojure-lsp/clojure-lsp#900] opened 2022-04-01 16:58 UTC
**Describe the bug**

Local namespace config is not respected for clj-kondo linter `clojure-lsp/unused-public-var`.

**To Reproduce**
1. Use clj-kondo namespace metadata to declare that the `unused-public-var` linter should be `:off`.
2. Define a public var. *(Do not otherwise use that var.)*
3. Note that linting invokes a warning.

```clojure
(ns skylize.foo
  {:clj-kondo/config '{:linters
                       {:clojure-lsp/unused-public-var {:level :off}
                        :unused-namespace {:level :off}}}}
  (:require
   ;; For a built-in linter, clj-kondo honors the configuration
   ;;   above. So even though `str` is never used, this gives
   ;;   no warning.
   [clojure.string :as str]))

;; Despite also setting `clojure-lsp/unused-public-var` to `off`
;;   this triggers a warning.
(def bar :baz) ;; --> Unused public var 'foo.foo/bar'...
```

**Expected behavior**
Clj-kondo namespace config should apply the same as it would for config in `.clj-kondo/config.edn`. In the specific case of the repro example, that means there should be no warning invoked for `bar`.

**Logs, etc.**
I can provide logs and/or screenshots if that would actually be helpful, but to me that seems unlikely to offer additional illumination.

**User details**
 - OS: ArchLinux
 - Editor VSCode (Calva)
 - Version: 2022.03.31-20.00.20

**Comment by ericdallo** [comment] 2022-04-01 17:11
Confirmed the issue, to be honest I didn't even know that was possible such ns config with clj-kondo, @borkdude maybe this is a clj-kondo issue with the `custom-fn-lint`?

**Comment by borkdude** [comment] 2022-04-01 17:41
I don't think it's possible to support this easily since the unused publics vars are linted outside of the namespace.

**Comment by ericdallo** [comment] 2022-04-01 18:21
Is there anything we could do to make that work, like changing the `reg-finding` we do inside custom-lint-fn to receive optional namespaces or something?

**Comment by borkdude** [comment] 2022-04-01 18:23
@ericdallo I think your linter could support a config to exclude namespaces.

**Comment by ericdallo** [comment] 2022-04-01 18:30
We [already do](https://clojure-lsp.io/settings/#clojure-lspunused-public-var), is just that this is the first thing that I'm aware of that differs from other clj-kondo linters, I was trying to make it work so all linters ways of configs from kondo would work with this one too

**Comment by borkdude** [comment] 2022-04-01 18:32
There is no reason to use the metadata config if a linter supports it in the config. And not all clj-kondo linters support it.

**Comment by ericdallo** [comment] 2022-04-01 18:48
Makes sense, @skylize will close this one, as we discussed this is already possible via clj-kondo config as described [here](https://clojure-lsp.io/settings/#clojure-lspunused-public-var)

**Closed by ericdallo** 2022-04-01 18:48 UTC
Labels: bug, waiting upstream, editor

**Comment by skylize** [comment] 2022-04-02 03:24
> There is no reason to use the metadata config if a linter supports it in the config.  @borkdude 

This statement has me thoroughly confused. Why did you bother implementing metadata config if you feel it has no purpose?

**Comment by borkdude** [comment] 2022-04-02 08:48
- Not all linters support ignoring usage from a certain namespace in their config. 
- Linters like unused-var are not localized to one namespace: whether they emit an error or not depends on usage in the whole project.
