### ISSUE TITLE
Consider `:lint-as` entries in `find-function-definition-name-loc`

### ISSUE THREAD

**Issue by MrEbbinghaus** [clojure-lsp/clojure-lsp#666] opened 2021-12-13 23:17 UTC
**Describe the bug**
For now [`find-function-definition-name-loc`](https://github.com/clojure-lsp/clojure-lsp/blob/111387c98364e302a9853a74bcf47b253801590c/src/clojure_lsp/refactor/edit.clj#L49) only considers a static set of symbols as "function definition".
Macros that behave like `defn` (e.g. [guardrails](https://github.com/fulcrologic/guardrails) `>defn`) are therefore treated incorrect.

This breaks a number of features:
- Code actions like "Create test for ..." are not working.
- Call hierarchies are not working

![image](https://user-images.githubusercontent.com/2965273/145902989-2fe3ef93-4e86-4135-9dee-cba5844df98a.png)

I propose, that entries like `:lint-as {com.fulcologic.guardrails/>defn clojure.core/defn}` are considered for this.

(I am not sure, if this should be considered a bug or a feature request. I would consider this a bug.)

**Comment by ericdallo** [comment] 2021-12-14 01:02
@MrEbbinghaus, checking kondo lint-as config could not be as reliable since the config could be on multiple places and we would need to make that code dynamically, maybe we can consider just adding guardrails function definitions to clojure-lsp? how many of those exists on guardrails?

**Comment by ericdallo** [comment] 2021-12-14 01:06
The issue is that code is not smart enough to check aliases and know its namespaces, we would need to change that a little bit

**Comment by ericdallo** [comment] 2021-12-14 01:15
Also, we could check `lint-as`, but that wouldn't work for clj-kondo hooks that are defined not via :lint-as but via some custom hook code

**Comment by ericdallo** [comment] 2021-12-14 02:55
I found a better way to handle that checking for all kondo var-definitions on the file, this should cover most if not all cases

**Comment by MrEbbinghaus** [comment] 2021-12-14 11:54
Thank you for addressing this so fast. 

I am aware, that this is a subpar solution that only patches some holes, but I think clojure-lsp could cover 90+% of use cases with just considering `:lint-as`. 

I have some comments:

> int-as config could not be as reliable since the config could be on multiple places

> Also, we could check lint-as, but that wouldn't work for clj-kondo hooks that are defined not via :lint-as but via some custom hook code

Would still be better to miss some, then not working at all, doesn't it?

Fun fact: I added a custom hook for `com.fulcologic.guardrails/>defn` myself... 
(I don't actually know what happens when you have a custom hook AND a `:lint-as` config for the same symbol.)

-----

> maybe we can consider just adding guardrails function definitions to clojure-lsp?

I think that would be a bad solution. Macros that extend `defn` or `def` are common in a lot of libraries. There are soooo many `def****` macros out there, and you don't want to maintain them all in clojure-lsp. 

Just looking at one of my `:lint-as` configs:
```
clojure.test.check.clojure-test/defspec                    clojure.core/def
clojure.test.check.properties/for-all                      clojure.core/let
com.fulcrologic.fulcro.routing.dynamic-routing/defrouter   clojure.core/defn
mount.core/defstate                                        clojure.core/def
nubank.workspaces.core/defcard                             clojure.core/def
com.fulcrologic.fulcro.algorithms.normalized-state/swap!-> clojure.core/->
failjure.core/attempt-all                                  clojure.core/let
```
So... You see the problem. 

----

For a more general solution:

> I found a better way to handle that checking for all kondo var-definitions on the file, this should cover most if not all cases

Considering that with Clojure you really could define a symbol in so many ways... And not all of them are function, but some of them are... I see that this is not a trivial issue. You would have a lot of false-positives with `find-function-definition-name-loc`. 

```clojure
; function:
(def foo {:a 1})

; not a function
(def foo "bar")

; not a function
(def my-pattern #"some-regex")

;And clojurescript makes it even more difficult
(extend-type js/RegExp
  IFn
  (-invoke 
    ([match s] (re-find match s))))

; now my-pattern is a function!
(my-pattern "clojurescript")
```

**Comment by ericdallo** [comment] 2021-12-14 16:42
Fixed on master, available on next release

**Closed** 2021-12-14 16:42 UTC
Labels: bug, editor
