### ISSUE TITLE
Java heap space limit reached

### ISSUE THREAD

**Issue by anonimitoraf** [clojure-lsp/clojure-lsp#268] opened 2021-01-24 04:14 UTC
When I start clojure-lsp (in Emacs, clojure-lsp version 2021.01.22-13.04.28) for a Clojurescript project, after a few minutes of attempting to start, I get the following error:

```
java.lang.OutOfMemoryError: Java heap space
	at clojure.lang.Tuple.create(Tuple.java:28)
	at clj_kondo.impl.namespace$get_namespace.invokeStatic(namespace.clj:343)
	at clj_kondo.impl.namespace$get_namespace.invoke(namespace.clj:342)
	at clj_kondo.impl.namespace$resolve_name.invokeStatic(namespace.clj:400)
	at clj_kondo.impl.namespace$resolve_name.invoke(namespace.clj:396)
	at clj_kondo.impl.analyzer$analyze_call.invokeStatic(analyzer.clj:1319)
	at clj_kondo.impl.analyzer$analyze_call.invoke(analyzer.clj:1302)
	at clj_kondo.impl.analyzer$analyze_expression_STAR__STAR_.invokeStatic(analyzer.clj:1781)
	at clj_kondo.impl.analyzer$analyze_expression_STAR__STAR_.invoke(analyzer.clj:1692)
	at clj_kondo.impl.analyzer$analyze_children$fn__17033.invoke(analyzer.clj:62)
	at clojure.core$map$fn__5866.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1792)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$mapcat.invokeStatic(core.clj:2783)
	at clojure.core$mapcat.doInvoke(core.clj:2783)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clj_kondo.impl.analyzer$analyze_children.invokeStatic(analyzer.clj:62)
	at clj_kondo.impl.analyzer$analyze_children.invoke(analyzer.clj:41)
	at clj_kondo.impl.analyzer$analyze_call.invokeStatic(analyzer.clj:1582)
	at clj_kondo.impl.analyzer$analyze_call.invoke(analyzer.clj:1302)
	at clj_kondo.impl.analyzer$analyze_expression_STAR__STAR_.invokeStatic(analyzer.clj:1781)
	at clj_kondo.impl.analyzer$analyze_expression_STAR__STAR_.invoke(analyzer.clj:1692)
	at clj_kondo.impl.analyzer$analyze_children$fn__17033.invoke(analyzer.clj:62)
	at clojure.core$map$fn__5866.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
```
Sample project: https://github.com/anonimitoraf/clojure-lsp-issue-repro

(If for any reason, you want to actually start the app, just run `lein watch` and then go to localhost:8280)

**Comment by ericdallo** [comment] 2021-01-24 04:19
Thanks, I'll check what we can do to improve it, this probably is happening after we merged #261

**Comment by anonimitoraf** [comment] 2021-01-24 04:26
Thanks. I wonder if it has to do with Javascript modules being more expensive to go through than Java ones?

**Comment by borkdude** [comment] 2021-01-24 08:30
A guess: maybe the locals analysis create a too huge in-memory data structure?

**Comment by borkdude** [comment] 2021-01-24 09:30
I notice linting this project's classpath takes about 2-3GB in memory on my machine. All the findings (and analysis, if you turn it on) is kept in memory until the end.

If this is only to warm up the cache, to save memory you could split the classpath into multiple chunks.

**Comment by anonimitoraf** [comment] 2021-01-24 10:30
Whoops, I pressed the wrong button.

@borkdude Is the classpath-splitting to be done within clojure-lsp or this project? Also, how does that help exactly?

**Comment by borkdude** [comment] 2021-01-24 10:51
@anonimitoraf Not exactly sure yet. What kind of memory do you have on your machine?

**Comment by anonimitoraf** [comment] 2021-01-24 11:02
@borkdude Do you mean the DDR_? If so, DDR4

**Comment by borkdude** [comment] 2021-01-24 11:04
@anonimitoraf Sorry for not being clear, I mean the amount. Can you monitor the memory usage in a process monitor/activity monitor while clj-kondo is linting with `rm -rf .clj-kondo/.cache && clj-kondo --lint $(lein classpath)` ?

**Comment by anonimitoraf** [comment] 2021-01-24 11:05
Oh right. I have 32GB in total. Ok, will do now

**Comment by anonimitoraf** [comment] 2021-01-24 11:14
It seems to fluctuate around 1.5 - 3.8GB
https://user-images.githubusercontent.com/15933322/105628528-846df680-5e91-11eb-95d3-50ed9fee3b82.mp4

**Comment by borkdude** [comment] 2021-01-24 11:34
So maybe the XMX flags are too low for LSP in this case? As suggested, this may be worked around by chunking the analysis in multiple portions or not turning on certain features during warm up like locals analysis. This should be done in LSP I think.

**Comment by ericdallo** [comment] 2021-01-24 13:47
I see @borkdude , how would be this chunk split? You mean, call clj-kondo to analyze a batch of folders than one call to the whole classpath?

**Comment by anonimitoraf** [comment] 2021-01-25 02:30
@ericdallo Given that this setting seems to be influenced by the project size, is there a viable way to make this configurable per-project?

**Comment by ericdallo** [comment] 2021-01-25 02:33
We release `clojure-lsp.jar` witch you can manually pass the xmx, but this is not good for final users, ATM we don't support that, and not sure how that would work since it's the jvm params, it's not clojure code where you can change it at runtime.
I like the batch idea from @borkdude but I not how would work that batch, if we should fix a number for paths to scan or something like that

**Comment by ericdallo** [comment] 2021-01-25 23:02
I'll try to make some testings sending batches of X files to clj-kondo analyzing to check if memory is improved

**Comment by ericdallo** [comment] 2021-01-26 00:59
I could not reproduce the OoO removing the cache and restarting multiple times with emacs: 🤔 
![image](https://user-images.githubusercontent.com/7820865/105784928-8949ad80-5f58-11eb-8c6e-eae7e663e78a.png)

**Comment by ericdallo** [comment] 2021-01-26 03:37
@anonimitoraf could you test if the memory issue is improved/fixed with #278? you can just run `lein bin` to generate the executable.

**Comment by borkdude** [comment] 2021-01-26 10:54
@ericdallo I pushed a commit to clj-kondo to make a call strict:

6ccdcf88bc50f24e6c12839fcaf3edee9be14249

Maybe that helps, I'm not sure.

**Comment by ericdallo** [comment] 2021-01-26 12:16
Hey @borkdude it looks to me that decrease memory indeed!
I made some tests with the #268 using that kondo version and it seems to improve, I'll keep using this branch for testing a few days, thanks for the help!

**Comment by ericdallo** [comment] 2021-01-26 12:44
Besides your project @anonimitoraf, I tested with a huge project from my work with is 2 times bigger and the memory didn't pass the 1.5G mark
Before(master):
![image](https://user-images.githubusercontent.com/7820865/105846507-09a0fa80-5fbb-11eb-8aa0-71d0e055cac9.png)

After (batch-kondo-analysis):
![image](https://user-images.githubusercontent.com/7820865/105845213-2ccaaa80-5fb9-11eb-9239-076979c40039.png)

**Comment by dcostaras** [comment] 2021-01-26 15:11
I have a project that OOMs consistently. I currently have `JAVA_TOOL_OPTIONS:  -XX:-OmitStackTraceInFastThrow -Dapple.awt.UIElement=true -Xms512m -Xmx4g` but I guess the `mx` is being overridden by clojure-lsp.



It's a commercial application based on https://github.com/fulcrologic/fulcro

If I start clojure-lsp in the template project (https://github.com/fulcrologic/fulcro-template) it consumes nearly 2GB but doesn't take too long to complete and then comes down after triggering a manual GC.

<img width="1318" alt="Screenshot 2021-01-26 at 14 58 07" src="https://user-images.githubusercontent.com/623750/105861705-ea1fc700-5fe6-11eb-8c25-1d0a967a780f.png">

In the commercial project it just keeps chugging and eventually starts spitting out errors

<img width="1325" alt="Screenshot 2021-01-26 at 15 02 13" src="https://user-images.githubusercontent.com/623750/105862253-7c27cf80-5fe7-11eb-8826-92e03c1f498d.png">

`*clojure-lsp::stderr*`
```
Picked up JAVA_TOOL_OPTIONS:  -XX:-OmitStackTraceInFastThrow -Dapple.awt.UIElement=true -Xms512m -Xmx4g
Jan 26, 2021 2:44:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2
Picked up JAVA_TOOL_OPTIONS:  -XX:-OmitStackTraceInFastThrow -Dapple.awt.UIElement=true -Xms512m -Xmx4g
Exception in thread "pool-2-thread-3" java.lang.OutOfMemoryError: Java heap space
	at clojure.lang.PersistentHashMap$BitmapIndexedNode.assoc(PersistentHashMap.java:888)
	at clojure.lang.PersistentHashMap$TransientHashMap.doAssoc(PersistentHashMap.java:327)
	at clojure.lang.ATransientMap.assoc(ATransientMap.java:64)
	at clojure.lang.PersistentHashMap.create(PersistentHashMap.java:78)
	at clojure.core$hash_map.invokeStatic(core.clj:387)
	at clojure.core$hash_map.doInvoke(core.clj:379)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clj_kondo.impl.rewrite_clj.parser.core$parse_delim$fn__5604.invoke(core.clj:49)
	at clj_kondo.impl.rewrite_clj.reader$read_repeatedly$fn__5155.invoke(reader.clj:133)
	at clojure.core$repeatedly$fn__6463.invoke(core.clj:5149)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$take_while$fn__5917.invoke(core.clj:2904)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5386.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3142)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at clj_kondo.impl.rewrite_clj.reader$read_repeatedly.invokeStatic(reader.clj:135)
	at clj_kondo.impl.rewrite_clj.reader$read_repeatedly.invoke(reader.clj:129)
	at clj_kondo.impl.rewrite_clj.parser.core$parse_delim.invokeStatic(core.clj:51)
	at clj_kondo.impl.rewrite_clj.parser.core$parse_delim.invoke(core.clj:45)
	at clj_kondo.impl.rewrite_clj.parser.core$fn__5668.invokeStatic(core.clj:249)
	at clj_kondo.impl.rewrite_clj.parser.core$fn__5668.invoke(core.clj:247)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clj_kondo.impl.rewrite_clj.reader$read_with_meta.invokeStatic(reader.clj:122)
	at clj_kondo.impl.rewrite_clj.reader$read_with_meta.invoke(reader.clj:118)
```

`clojure-lsp.out`
```
INFO  clojure-lsp.main: Starting server...
INFO  clojure-lsp.main: ====== LSP nrepl server started on port 63400
INFO  clojure-lsp.main: Initializing...
WARN  clojure-lsp.db: Could not load db [SQLITE_ERROR] SQL error or missing database (no such table: project)
INFO  clojure-lsp.crawler: Analyzing 217 paths with clj-kondo...
INFO  clojure-lsp.crawler: Paths analyzed, took 20.211 secs. Caching for next startups...
INFO  clojure-lsp.crawler: Analyzing 2 paths with clj-kondo...
INFO  clojure-lsp.crawler: Paths analyzed, took 0.113 secs. Caching for next startups...
ERROR clojure-lsp.crawler: Cannot find position for: let* {:filename "/Users/donavan/src/fulcro-template/src/main/app/server_components/pathom.clj", :row nil, :col nil, :from app.server-components.pathom, :to clojure.core, :name let*, :arity 2, :bucket :var-usages} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:filename "/Users/donavan/src/fulcro-template/src/main/app/server_components/pathom.clj", :row nil, :col nil, :from app.server-components.pathom, :to clojure.core, :name fn*, :arity 2, :bucket :var-usages} nil
ERROR clojure-lsp.crawler: Cannot find position for: let* {:filename "/Users/donavan/src/fulcro-template/src/main/app/server_components/pathom.clj", :row nil, :col nil, :from app.server-components.pathom, :to clojure.core, :name let*, :arity 2, :bucket :var-usages} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:filename "/Users/donavan/src/fulcro-template/src/main/app/server_components/pathom.clj", :row nil, :col nil, :from app.server-components.pathom, :to clojure.core, :name fn*, :arity 2, :bucket :var-usages} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/book/chapter_1.cljs", :from app.ui.book.chapter-1, :col nil, :from-var Root, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: -> {:name ->, :filename "/Users/donavan/src/fulcro-template/src/main/app/model/session.cljs", :from app.model.session, :macro true, :col nil, :from-var process-session-result, :arity 2, :varargs-min-arity 1, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: if {:name if, :filename "/Users/donavan/src/fulcro-template/src/main/app/model/session.cljs", :from app.model.session, :col nil, :from-var process-session-result, :arity 3, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: -> {:name ->, :filename "/Users/donavan/src/fulcro-template/src/main/app/model/session.cljs", :from app.model.session, :macro true, :col nil, :from-var process-session-result, :arity 2, :varargs-min-arity 1, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: if {:name if, :filename "/Users/donavan/src/fulcro-template/src/main/app/model/session.cljs", :from app.model.session, :col nil, :from-var process-session-result, :arity 3, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: let {:name let, :filename "/Users/donavan/src/fulcro-template/src/main/app/model/session.cljs", :from app.model.session, :macro true, :col nil, :from-var process-session-result, :arity 2, :varargs-min-arity 1, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: let* {:filename "/Users/donavan/src/fulcro-template/src/main/app/model/session.cljs", :row nil, :col nil, :from app.model.session, :to cljs.core, :name let*, :arity 2, :bucket :var-usages} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:filename "/Users/donavan/src/fulcro-template/src/main/app/model/session.cljs", :row nil, :col nil, :from app.model.session, :to cljs.core, :name fn*, :arity 2, :bucket :var-usages} nil
ERROR clojure-lsp.crawler: Cannot find position for: let* {:filename "/Users/donavan/src/fulcro-template/src/main/app/model/session.cljs", :row nil, :col nil, :from app.model.session, :to cljs.core, :name let*, :arity 2, :bucket :var-usages} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:filename "/Users/donavan/src/fulcro-template/src/main/app/model/session.cljs", :row nil, :col nil, :from app.model.session, :to cljs.core, :name fn*, :arity 2, :bucket :var-usages} nil
ERROR clojure-lsp.crawler: Cannot find position for: let* {:name let*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Signup, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Signup, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: let* {:name let*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Signup, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Signup, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Signup, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: let* {:name let*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Signup, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Signup, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Login, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Login, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: let* {:name let*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Login, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Login, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: let* {:name let*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Login, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/main/app/ui/root.cljs", :from app.ui.root, :col nil, :from-var Login, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
ERROR clojure-lsp.crawler: Cannot find position for: fn* {:name fn*, :filename "/Users/donavan/src/fulcro-template/src/workspaces/app/demo_ws.cljs", :from app.demo-ws, :col nil, :from-var FulcroDemo, :arity 2, :bucket :var-usages, :row nil, :to cljs.core} nil
DEBUG clojure-lsp.main: :initialize 40934 ()
INFO  clojure-lsp.main: Initialized #object[org.eclipse.lsp4j.InitializedParams 0x493e6938 InitializedParams [
]]
DEBUG clojure-lsp.main: :documentSymbol 2 ([:codeAction #{176174735679791}])
INFO  clojure-lsp.main: Starting server...
INFO  clojure-lsp.main: ====== LSP nrepl server started on port 63822
INFO  clojure-lsp.main: Initializing...
WARN  clojure-lsp.db: Could not load db [SQLITE_ERROR] SQL error or missing database (no such table: project)
INFO  clojure-lsp.crawler: Analyzing 447 paths with clj-kondo...
```

JVM macOS arm64 (https://www.azul.com/downloads/zulu-community/?os=macos&architecture=arm-64-bit&package=jdk)
```
❯ java --version
Picked up JAVA_TOOL_OPTIONS:  -XX:-OmitStackTraceInFastThrow -Dapple.awt.UIElement=true
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+1021-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+1021-CA (build 11.0.9.1+1-LTS, mixed mode)
```

I'm not much of a JVM developer but happy to help debug.

**Comment by dcostaras** [comment] 2021-01-26 15:37
So it seems to have worked after starting it up for, maybe, the 5th time?

One thing I've noticed is that the mx setting now seems to be respecting the 4GB that I've set it to. I'm not how that has happened TBH (also I realise that clojure-lsp is using it's own JVM, not the Azul one I mentioned above)

<img width="873" alt="Screenshot 2021-01-26 at 15 36 32" src="https://user-images.githubusercontent.com/623750/105866804-49340a80-5fec-11eb-911d-867b0dc25eb6.png">

**Comment by ericdallo** [comment] 2021-01-26 15:38
@dcostaras thank you very much for your input, would you mind testing with the #268 PR?
You can gerentes the release with `lein bin`

**Comment by dcostaras** [comment] 2021-01-26 15:40
I'm guessing you mean #278?

**Comment by ericdallo** [comment] 2021-01-26 16:07
Yep, sorry, I'm on mobile : 😅

**Comment by dcostaras** [comment] 2021-01-26 16:23
Using the above build. I did a manual GC after the lsp server initialised (The point where the used heap stabilised). Seems to work much better 👍 

<img width="1963" alt="Screenshot 2021-01-26 at 16 21 21" src="https://user-images.githubusercontent.com/623750/105872653-8dc2a480-5ff2-11eb-9dab-ac73d94ba773.png">

**Comment by dcostaras** [comment] 2021-01-26 16:26
TBC: I `rm -rf .lsp .clj-kondo .cp-cache` before opening the project in emacs. And it took about 2mins to initialise.

**Comment by ericdallo** [comment] 2021-01-26 16:47
Nice @dcostaras so no OOM right? also, is there any reason for you to manually do a manual GC? do you get a OOM without that?

**Comment by dcostaras** [comment] 2021-01-26 16:56
Yeah, went from 100% CPU for 16mins until OOM with current master build to finishing in 2mins (didn't watch CPU) without OOM. No reason to do a manual GC other than it was a button and I was curious to see what would happen if I pushed it :)

**Comment by ericdallo** [comment] 2021-01-26 16:57
hahaha, sweet!
I'll keep testing today, if everything runs well, I'll merge it, thanks for the help!

**Comment by dcostaras** [comment] 2021-01-26 17:14
So with the 2GB limit it stills handles beautifully

<img width="1964" alt="Screenshot 2021-01-26 at 17 06 02" src="https://user-images.githubusercontent.com/623750/105878465-fe6cbf80-5ff8-11eb-9362-f9819b2525c1.png">

CPU (bump in the middle; with master it was pegged at 100% until it failed)

<img width="597" alt="Screenshot 2021-01-26 at 17 05 54" src="https://user-images.githubusercontent.com/623750/105878495-03ca0a00-5ff9-11eb-8314-f2bbefc3acde.png">

Nicely done! Thanks for clojure-lsp (signed up on open collective 👍 )

**Comment by ericdallo** [comment] 2021-01-26 17:23
Thank you @dcostaras, glad to see users happy :D

**Comment by anonimitoraf** [comment] 2021-01-26 20:06
Hey @ericdallo, I tried 2021.01.25-22.56.05 and it doesn't crash at startup anymore :) Memory usage peaked at around a bit less than 2GB

I wonder though why it used much less memory in your machine. Which OS are you using?

**Comment by ericdallo** [comment] 2021-01-26 20:09
Cool, that's great news :D
I'll release the fix later today, thank you everybody for the help

BTW: `NixOS on a Asus zenbook 3 deluxe 16 RAM`

**Comment by anonimitoraf** [comment] 2021-01-26 20:12
Thanks so much.

Right, I'm on Ubuntu 20.04. Strange... Follow-up question, which program did you use to graph Mem/CPU usage? I couldn't find any linux tools to do so (that seem easy to set up)

**Comment by ericdallo** [comment] 2021-01-26 20:15
old and working `jconsole` from oracle :)
There are better programs for other JDKs though

**Comment by anonimitoraf** [comment] 2021-01-26 20:23
Weird, no jconsole
![image](https://user-images.githubusercontent.com/15933322/105900653-75916a80-6070-11eb-8d81-48bf53a9fc0c.png)

Any other tools you can suggest? (I rarely have the need to profile stuff so usually htop is enough for my other needs)

**Comment by ericdallo** [comment] 2021-01-26 20:41
odd: https://openjdk.java.net/tools/svc/jconsole/

I recommend https://visualvm.github.io/ also

**Comment by ericdallo** [comment] 2021-01-26 22:34
FIxed on latest release

**Closed by ericdallo** 2021-01-26 22:34 UTC
Labels: performance
