### ISSUE TITLE
`clojure-lsp --version` doesn't print anything

### ISSUE THREAD

**Issue by kommen** [clojure-lsp/clojure-lsp#519] opened 2021-08-16 15:55 UTC
On the command line, `clojure-lsp --version` doesn't print the version information.

**To Reproduce** 

```
$ brew install clojure-lsp/brew/clojure-lsp-native
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 2 casks.

==> Installing clojure-lsp-native from clojure-lsp/brew
==> Downloading https://github.com/clojure-lsp/clojure-lsp/releases/download/2021.08.16-14.47.54/clojure-lsp-native-macos-amd64.zip
Already downloaded: ~/Library/Caches/Homebrew/downloads/d1166765549337afbeace88fd2f516a0eb9f0c1313ee9d1b5c007663b219b052--clojure-lsp-native-macos-amd64.zip
🍺  /usr/local/Cellar/clojure-lsp-native/2021.08.16-14.47.54: 3 files, 119.9MB, built in 4 seconds
$ which clojure-lsp                               
/usr/local/bin/clojure-lsp
$ clojure-lsp --version 
$ 
```

**Expected behavior**
Version information printed

Other:
```
macOS 10.15.7 (19H1323)
```

**Comment by ericdallo** [comment] 2021-08-16 16:12
Yeah, I'm having issue with releasing clojure-lsp, I'll fix it ASAP

**Comment by ericdallo** [comment] 2021-08-16 16:16
@kommen does the issue is just the version or clojure-lsp doesn't work for your editor as well?

**Comment by ericdallo** [comment] 2021-08-16 16:20
it seems to be a issue with graalvm compiled binary, but just for the --version

**Comment by ericdallo** [comment] 2021-08-16 17:16
Fixed on next release that is being released right now

**Closed by ericdallo** 2021-08-16 17:16 UTC
Labels: bug, graalvm, API
