### ISSUE TITLE
Doesn't work in monorepos

### ISSUE THREAD

**Issue by agzam** [clojure-lsp/clojure-lsp#191] opened 2020-10-14 22:23 UTC
Clojure-lsp doesn't seem to be "know" how to work with monorepos managed by lein-monolith.

For example: if you have a dependency to a lib project that is within the monorepo, using `lsp-find-references` on `my-lib.core/my-fn` wouldn't find `my-fn`. Again:

- there's a monorepo
- it has a sub-project called `my-lib`. There's a function `my-lib.core/my_fn`
- there's another sub-project: `my-service` that has a namespace that imports and uses `my-lib.core/my_fn`
- Now, when I use `lsp-find-references`, with cursor being on `my-fn `, I of course expect it to be found in `my-lib.core/my-fn`, but it doesn't.

Is that something that can be fixed or clojure-lsp is not designed to work with `lein-monolith`?

**Comment by ericdallo** [comment] 2020-10-15 00:59
I'm not sure if this is a bug on clojure-lsp, @agzam can you confirm if your project is the mono-repo root and not a subproject via `lsp-describe-session`? otherwise you can `lsp-workspace-folders-remove` then `lsp` again

**Comment by ericdallo** [comment] 2020-10-15 16:01
Because this is client's responsibility (in this case, lsp-mode) send the files for the server analyzes it.
In this case I think it's correct, the server is watching the root project.
@snoe do you think this could be related to a custom classpath?

**Comment by bpringe** [comment] 2021-01-06 18:10
Does the `project-specs` config setting help in this case, if you specify each project there? Like the below, but specifying each project and the respective `:project-path`. @kstehn (This question is for you as well.)

```edn
{:project-specs [{:project-path "deps.edn"
                  :classpath-cmd ["clj" "-Spath"]}]}
```

**Comment by agzam** [comment] 2021-01-06 19:48
@bpringe what is a `project-specs` config? Where should I have this map? I can't find anything in the documentation.

**Comment by ericdallo** [comment] 2021-01-06 19:55
@agzam you can find it here: https://github.com/clojure-lsp/clojure-lsp#initializationoptions

**Comment by bpringe** [comment] 2021-01-06 22:03
@ericdallo Do you think it would be a good idea to not collapse the settings section in the readme? I also had done a search on the page for that and didn't find it, but knew I had seen it before so I went down and expanded the settings section. It may be a good idea to not expand other sections as well, if you agree.

**Comment by ericdallo** [comment] 2021-01-06 22:07
Hum, not sure, it was all expanded before and it was a mess :/
We can think of other ways to organize that also, maybe move to other files just like `clj-kondo`, but user would need to find in the correct section anyway

**Comment by bpringe** [comment] 2021-01-06 22:15
I think everything expanded but with a table of contents would be helpful. It makes searching for things via `ctrl+f` in the browser easy. Just something to think about.

**Comment by agzam** [comment] 2021-01-06 22:27
The problem is not such that search ignores collapsed blocks. That's a minor thing compared to what the readme says:

> It is possible to pass some options to clojure-lsp through clients' `InitializationOptions`. Options are a map with keys.

And that's it. It doesn't say where this map goes, doesn't use any examples, etc. And for the life of me after several minutes of searching I couldn't find how to set this up. And I do remember, long time ago when I just started using lsp I knew how to do that. Now I forgot.

**Comment by ericdallo** [comment] 2021-01-06 22:34
@agzam I agree with you and it's on my backlog improve that section!

The issue is that there are 2 ways to pass that map:
- via `InitializationOptions` which clients should send that, like Calva, lsp-mode etc
- via project or global settings said it [here](https://github.com/clojure-lsp/clojure-lsp#global) which is your case

The docs are not clear related to that, I really change that soon

**Comment by dawranliou** [comment] 2021-01-30 14:15
I finally got my monorepo to work with clojure-lsp. However, instead of `lsp-mode` I'm using `eglot` here. There are still caveats about my setup, which I mentioned at the bottom, so any feedback is welcome!

The root cause of my problem was the usage of emacs's `project.el` to locate the project root. For a monorepo, the project root is the monorepo itself. Initialing clojure-lsp with the monorepo location doesn't help the crawler to find the source code and the jar files. My setup below involves customizing `project.el` to send the sub-project location to clojure-lsp instead of the default monorepo location.

I have this helper function defined in my config and append it to the `project-find-functions`:

```elisp
(defun my/project-try-clojure (dir)
  "Try to locate a clojure project."
  (when-let ((found (clojure-project-dir)))
    (cons 'transient found)))

;; In my setting, I actually do this in the sub-project's .dir-locals file
(add-to-list 'project-find-functions 'my/project-try-clojure)
```

Doing so, the clojure-lsp will be initialized with the sub-project's root dir. (It took a while for the clojure-lsp crawler to go through all the jarfiles for the first time so I also bumped the `eglot-connect-timeout`.)

However, here's the caveat. This setting inevitably modified the project root for all of the `project.el`'s commands. The commands like `project-find-file` will only find files in the sub-directory and I don't know how to solve this yet! Also I still have an issue finding the definition from another sub-project.

Hope my setting shed some light on the problem with `lsp-mode`.

**Comment by ericdallo** [comment] 2021-01-30 17:54
@dawranliou lsp-mode works too for subproject, you just need to pre-select the correct project root on the first run and don't need any config regarding project.el or something like that

**Comment by dawranliou** [comment] 2021-02-01 01:33
Just want to post [my updated settings](https://github.com/dawranliou/emacs.d/commit/8b3bae6edd40a5d6e0ec75437b91036b0412e879) for eglot in case someone is looking. Here I'm using an advice function to update the `project-find-functions` value in the dynamic scope of `eglot--guess-contact` so my other `project.el` commands are not affected.

```elisp
(defun my/project-try-clojure (dir)
  "Try to locate a clojure project."
  (when-let ((found (clojure-project-dir)))
    (cons 'transient found)))

(defun my/eglot--guess-contact-clojure-project-monorepo (orig-fun &rest args)
  "Fix project-root for clojure monorepos."
  (let ((project-find-functions
         (cons 'my/project-try-clojure project-find-functions)))
    (apply orig-fun args)))

(advice-add 'eglot--guess-contact :around
            #'my/eglot--guess-contact-clojure-project-monorepo)
```

**Comment by ericdallo** [comment] 2021-06-18 20:06
I tested the [example project](https://github.com/amperity/lein-monolith/tree/master/example) from `lein-monolith`, creating a function in a subproject and using in another subproject and everything works fine with latest clojure-lsp and lsp-mode, the key here to make it work is to import the mono-repo root as the project root for lsp-mode (in this case lein-monolilth/example was the imported project-root).

LMK if any issues with that.

**Closed by ericdallo** 2021-06-18 20:06 UTC
Labels: help wanted, question

**Comment by bendlas** [comment] 2021-09-13 16:34
I tried adding `lein-monolith` to plugins, for a monorepo that I'm working with. This shows the same behavior as before adding `lein-monolith`:

Cross-referencing files that already have been analyzed works fine. However, discovering all the project source files does not. Thus, e.g. if I run `lsp-find-references`, the result depends on what files I happen to have visited.

**Comment by kstehn** [comment] 2021-09-13 16:39
I had to define a config for the lsp in `.lsp/config.edn`.
There i referenced all source-paths that needs to be analyzed.

Example:
```clojure
{:source-paths #{"foo/src/clj" "bar/src/clj"}
 :project-specs [{:project-path "project.clj"
                           :classpath-cmd ["lein.bat" "classpath"]}]
```

The classpath-cmd is only for windows relevant, without this i didn't got this working.

**Comment by ericdallo** [comment] 2021-09-13 17:01
@kstehn do you need to do that with lein bat for every clojure project? If so, could you open a new issue where we can work on making clojure-lsp understand lein for windows

**Comment by ericdallo** [comment] 2021-09-13 17:02
@bendlas we can improve clojure-lsp support for lein-monolilth to not need any extra config I think, would you mind creating a new issue with details and a minimal repro project?

**Comment by ericdallo** [comment] 2021-09-13 18:22
Yeah, We did some windows improvements some time ago :)
Nice
