### ISSUE TITLE
Small freezes regression during editing on big buffers

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#1240] opened 2022-09-11 23:59 UTC
**Describe the bug**

@borkdude noticed small freezes on emacs while coding on squint-cljs/squint, I can confirm the issue, it seems to be a regression [since 2022.06.22-14.09.50 tag ](https://github.com/clojure-lsp/clojure-lsp/compare/2022.06.22-14.09.50...2022.09.01-15.27.31).

After some debugging, I noticed it's related to [process-after-all-changes](https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/src/clojure_lsp/handlers.clj#L45), the issue is gone only after commenting all usages of that macro.

@mainej mentioned that it may be related with lsp4clj migration, but I suspect it could be related to the change on that macro where it supports waiting for multiple URIs, not only one.

**To Reproduce**
- Clone [squint-cljs/quint](https://github.com/squint-cljs/squint)
- Open compiler.cljc
- add a new line after line 491, and start writing `x`s slowly to repro the slowness/freezing

**Expected behavior**
Do not block editor or avoid freezing

**Comment by ericdallo** [comment] 2022-09-12 00:05
The issue doesn't happen on previous release, so it's probably [related to lsp4clj migration](https://github.com/clojure-lsp/clojure-lsp/compare/2022.07.24-18.25.43...2022.09.01-15.27.31).

**Comment by mainej** [comment] 2022-09-14 18:31
I don't have a fix for this, but I've found something that I think must be relevant. Before the lsp4clj migration you can find logs lines like the following:

```
2022-09-13T23:43:29.314Z  INFO [clojure-lsp.handlers:?] - :semantic-tokens-full 61ms - waited 5002ms
2022-09-13T23:43:29.382Z  INFO [clojure-lsp.handlers:?] - :semantic-tokens-full 82ms - waited 5823ms
```
Labeling these as request A and B respectively, and doing the math, the sequence of events was:
```
2022-09-13T23:43:23.477 received B
2022-09-13T23:43:24.251 received A 
2022-09-13T23:43:29.314 responded to A
2022-09-13T23:43:29.382 responded to B
```

So, it appears that before the migration lsp4clj was processing the messages out of order. Going back to study the code, [lsp4j forward each request to lsp4clj](https://github.com/eclipse/lsp4j/blob/04b0c6112f0a94140e22b8b15bb5a90d5a0ed851/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/RemoteEndpoint.java#L257) as soon as it received it, even before replying to earlier requests. It expected to be returned a CompletableFuture, which [lsp4clj wrapped around most clojure-lsp request handlers](https://github.com/clojure-lsp/lsp4clj/blob/fe8782941fd871921d55349b9f7803ac0dc8595d/server/src/lsp4clj/core.clj#L100-L102). The handler code was run in a future, and so the responses could be delivered out of order.

The fact that lsp4clj was processing messages out of order surprises me. During the migration, I started off processing messages in parallel with `async/pipeline-blocking`. At some point I realized that caused problems (unfortunately, I don't remember and didn't document what kind of problems) and so I [removed that parallelism](https://github.com/clojure-lsp/lsp4clj/commit/6996fdbaefe743431994839db07676a24052cd25). Now lsp4clj waits until clojure-lsp produces a response before giving it the next message, so in the new world, the message order would be: 
```
received B
responded to B
received A
responded to A
```

You can see this in the new logs—before, after a `did-change`, several requests logged a "waited Xms", but now only one request does, and the logs for all the other requests follow it.

I think this is somehow relevant to the freezing. Clients generally follow the pattern of sending a `did-change` notification, quickly followed by several requests for other things such as semantic tokens or code lenses. Some, though not all, of those requests sleep waiting for the analysis triggered by `did-change`. Suppose we call two of these requests that sleep "A" and "B". We used to have this sequence:

```
input A and B
put A and B on two separate threads
in both threads sleep 500ms waiting for analysis
process A and B in parallel
output A and B (in non-deterministic order)
```
But now lsp4clj enforces this sequence:
```
input A
sleep 500ms waiting for analysis
process A
output A
input B (no sleep necessary, because analysis is done)
process B
output B
```

Because the processing no longer happens in parallel, B's response is slightly delayed as compared to before the migration. But these requests are generally fast, so I'm not sure that's actually the cause of the freezes. Suppose A and B both take 30ms to process. Before both requests would get responses 530ms after they were initially (essentially simultaneously) placed. Now, A's response is 530ms after, and B's is 560ms after. That is, B's response is 5% slower than before. I'm not sure that's a big enough change to notice.

Instead, it's possible that the freezes are because of how this interacts with requests that _don't_ sleep waiting for analysis. This time let "B" be a request that **doesn't** sleep. It used to be that we would:

```
input A and B
put A and B on two separate threads
process B immediately, but sleep in A's thread
output B
output A
```

But now we don't even start processing B until A has slept, been processed, and been output. So, we used to respond to B 30ms after the `did-change`, but now we respond to it 560ms after. That's a very significant new pause—B's response is 1866% slower—and so I wonder if that manifests as lag that we weren't seeing before.

To fix this, lsp4clj could do what lsp4j was doing—processing requests in parallel. But I'm not sure we **should** do that. I could make an argument that what lsp4j was doing was wrong. The [spec says](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#messageOrdering), "Responses to requests should be sent in roughly the same order as the requests appear". _Roughly_ is a very vague instruction, but lsp4j doesn't even attempt to follow this guidance. Maybe we now follow the guidance too strictly. Perhaps there's middle ground.

That's as far as I've gotten. I think I want to look at which requests sleep and which don't. Perhaps I can pinpoint one that is now being processed much later than it used to. But after finding that, what should I do? Research whether lsp4clj could process some requests out of order? Or research whether lsp-mode really needs to block for that request?

**Comment by borkdude** [comment] 2022-09-14 18:42
I'm not deeply aware of how the internals work right now, but just for my understanding: why is my editor freezing because of how a server behaves? Even if the server's main thread is blocked for a second, I should still be able to type, while maybe not having updated diagnostics for a second? Are the requests in emacs made synchronously?

**Comment by borkdude** [comment] 2022-09-14 18:45
If the lsp server still behaves as it did before, which was imo better, maybe it's not unreasonable to just do what lsp4j did?

**Comment by ericdallo** [comment] 2022-09-15 13:09
@borkdude yeah, maybe this is something to be fixed on lsp-mode, we could test if vscode behaves similar, if not, we could open a issue on lsp-mode.

@mainej makes sense, I agree that we are now following the spec, and finding a middle ground would be better, but if we don't find it, I'm ok going back to unordered for now as we were not even aware of that because we had no bug reports, and we could test rollback to ordered if we improve this performance issue.

**Comment by mainej** [comment] 2022-09-17 16:50
I can't get Calva to exhibit the freezes, so I'd guess it processes requests more asynchronously than Emacs. However, the freezing is subtle on my Emacs—I have to type at a very specific speed and even then I notice freezes intermittently and only for a brief moment. So, I'm not sure that what I'm seeing in Calva is correct. @ericdallo or @borkdude could you check whether you can reproduce the freezes in Calva?

Even if the freezes can be attributed to lsp-mode, we may still want to change clojure-lsp and lsp4clj. There's a related problem that syntax highlighting is slower in Calva now. It used to be that if you typed `xxxxxxxxxxx` at a rate of about 3 to 4 characters per second, the syntax highlighting would catch up to you in chunks—the red squiggle would be added under the first 3 characters, say, then extended to 4 more, and so on. The wait time between each extension seemed to be about the same as the analysis time. Now the red squiggle is extended one character at a time. The wait time between each extension is the same, so there's a long wait until the squiggle covers the whole sequence of `x`es. It does catch up eventually and typing doesn't seem to block—but it's not ideal.

**Comment by ericdallo** [comment] 2022-09-17 17:18
@mainej I'd like to add that this week I noticed those freezes more frequently in my projects from my work, it's really like clijure-lsp is processing one request at time.
I do think we should fix lsp-mode to handle that (even thinking this may be hard as Emacs is single thread), but making clojure-lsp process multiple threads for each request even out of order seems something we should think about it

**Comment by mainej** [comment] 2022-09-17 19:10
> this week I noticed those freezes more frequently

@ericdallo good to know. Sorry about that.

> it's really like clojure-lsp is processing one request at time

It is. :/

> making clojure-lsp process multiple threads for each request even out of order seems something we should think about it

I agree. I'm working on that. At first I thought we could change just lsp4clj, but I think clojure-lsp will have to change too.

**Comment by ericdallo** [comment] 2022-09-17 19:12
@mainej no worries, I'm glad we are aware and found the reason, LMK if you need any help on that investigation or help to test anything

**Comment by mainej** [comment] 2022-09-18 06:18
Thanks @ericdallo. I don't get typing freezes in Calva, but I do get very slow diagnostics, as described above. Would you check whether you see the same thing?

**Comment by ericdallo** [comment] 2022-09-18 15:20
@mainej I can repro the really slow diagnostics + semantic tokens on Calva indeed, way slower compared with the previous release

**Comment by borkdude** [comment] 2022-09-19 21:37
@ribelo reported on Slack in the clojure-lsp channel that he is also seeing freezes in neovim, but not when he reverts to an older version `2022.07.24-18.25.43`

**Closed** 2022-09-23 23:04 UTC
Labels: bug, performance, editor

**Comment by ericdallo** [comment] 2022-09-24 14:01
For anyone interested on this issue, it was merged on lsp4clj and made the necessary changes on clojure-lsp so it's available on nightly builds, please let us know if any issue. Kudos to @mainej for the huge help!

c/c @borkdude
