### ISSUE TITLE
add-missing-require code action should suggest already referred symbols in other files

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#222] opened 2020-12-27 19:49 UTC
You can see here (from Calva), that this namespace is not required, but there are "No quick fixes available."

![image](https://user-images.githubusercontent.com/12722744/103178621-2cfc4c80-4839-11eb-8d8f-7097282378fa.png)

If add-missing-lib-spec were sent as `CodeActionKind` `quickfix` this would allow it to be an option the user could select there (I'm pretty sure).

[Link to the relevant place in the spec (scroll some)](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction)

**Comment by ericdallo** [comment] 2020-12-27 20:56
We already do that, but we only send that code action when we know how import that alias.
If you never imported `util` in any other file form that project, there is no way `clojure-lsp` know what ns import.

**Comment by ericdallo** [comment] 2020-12-27 23:56
We can also add some known ns to `clojure-lsp`, like `clojure.core`, `clojure.string`, `clojure.set`, WDYT @bpringe ?

**Comment by bpringe** [comment] 2020-12-28 01:11
Oh... I see. I suppose this would be good, but seems low priority. Feel free to close if you want.

**Comment by bpringe** [comment] 2020-12-28 01:18
> We already do that, but we only send that code action when we know how import that alias.

I see what you're saying here. I seem to remember some editor functionality for say, JS, that would somehow know if you were using something from another non imported package. I guess for example if you have a reference to `my-func` and there's no `my-func` in the file, but clojure-lsp's db has a `my-func` in `my-ns`, couldn't it add a required like `[my-ns :refer [my-func]]`?

It could also guess make up an alias based off the ns, and add the alias to the usage, but that starts to get complex. Just throwing out some thoughts.

**Comment by ericdallo** [comment] 2020-12-28 01:29
Yes, for some cases it's very complex, but for others like `refers`, it may be a valid feature.

**Comment by ericdallo** [comment] 2021-01-08 00:48
FYI, it's now supported adding common requires/imports as I said [here[(https://github.com/clojure-lsp/clojure-lsp/issues/222#issuecomment-751531006) :)

I'll keep the issue open for your last comment as a feature

**Comment by ericdallo** [comment] 2021-02-06 01:46
Closing this since is a duplicate of #302

**Closed by ericdallo** 2021-02-06 01:46 UTC
Labels: enhancement
